### ISSUE TITLE
Icon URL in YAML

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-presidio#16]
Add this to your Quarkus Extension YAML so it appears with the MS open Source logo.

```
icon-url: "https://opensource.microsoft.com/assets/images/svgs/microsoft-logo-no-text.svg"
```

![image](https://github.com/user-attachments/assets/b889e7c6-aa5a-448f-bf69-d6bf4b6d6155)

**Comment by lordofthejars** [comment]
Thanks, updated.
